# vim: ft=tmux
# Configure and load catppuccin prior to plugin load if it exists

# Set global catppuccin settings:
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

%hidden _HAS_PLUGIN="${XDG_CONFIG_HOME}/tmux/scripts/has_plugin"
%hidden _LOAD_CATPPUCCIN="${XDG_CONFIG_HOME}/tmux/scripts/load_catppuccin"

# If tmuxedo has loaded the plugin 
if-shell "$_HAS_PLUGIN catppuccin_tmux" {
  # modified from:
  # https://github.com/catppuccin/tmux?tab=readme-ov-file#recommended-default-configuration
  run-shell "$_LOAD_CATPPUCCIN"
  set -g status-right-length 100
  set -g status-left-length 100
  set -g status-left ""
  set -g status-right "#{E:@catppuccin_status_application}"
  # set -agF status-right "#{E:@catppuccin_status_cpu}"
  set -ag status-right "#{E:@catppuccin_status_session}"
  set -ag status-right "#{E:@catppuccin_status_uptime}"
  #  set -agF status-right "#{E:@catppuccin_status_battery}"
} {
  display-message "The catppuccin plugin needs to be downloaded  not found!"
}

