# vim: ft=tmux
# Settings for tmux-ressurrect 

set -g @resurrect-dir "~/.local/share/tmux/resurrect"
set -g @ressurect-strategy-vim 'session'
set -g @ressurect-strategy-nvim 'session'

# Let us restore lazygit if it is in use.
set -g @resurrect-processes '"~lazygit"'

# Hack to fix entries for bob-nvim
# 
# Modified from this solution to get appimage nvim working with nix.
# https://github.com/tmux-plugins/tmux-resurrect/issues/394#issuecomment-1224204011
set -g @resurrect-hook-post-save-all 'sed --follow-symlink -i "s%$HOME/.local/share/bob.*nvim%nvim%" ~/.local/share/tmux/resurrect/last'
