# vim: ft=tmux
# Settings for tmux-ressurrect 

set -g @resurrect-dir "~/.local/share/tmux/resurrect"
# set -g @ressurect-strategy-vim 'session'
# set -g @ressurect-strategy-nvim 'session'

# Note: because bob-nvim installs nvim in a weird location, we need to releax
# the nvim name matcher to restore nvim sessions/locations.
set -g @resurrect-processes '"~nvim" "~lazygit"'
