tmux-plugins/tmux-continuum
tmux-plugins/tmux-sensible
tmux-plugins/tmux-copycat
tmux-plugins/tmux-sessionist
tmux-plugins/tmux-logging
tmux-plugins/tmux-yank
catppuccin/tmux
tmux-plugins/tmux-resurrect
tmux-plugins/tmux-pain-control
