# vim: ft=tmux

# Enable clipboard support
set-option -s allow-passthrough on
set-option -s set-clipboard on
# Need a hidden reference to the tmux config path for variable expansion here.
%hidden _IS_MOSH="${XDG_CONFIG_HOME}/tmux/scripts/is_mosh"

# If _IS_MOSH then we need to apply the mosh specific hacks. ET and ssh don't
# require this.
if-shell "$_IS_MOSH" {
  # OSC-52 override for mosh support
  # see: https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b
  set-option -ga terminal-overrides ",vte*:Ms=\\E]52;c;%p2%s\\7"
  set-option -ga terminal-overrides ",xterm-*:Ms=\\E]52;c;%p2%s\\7"
} 
