#!/bin/bash

get_dir_for_plugin() {
  local xdg_config_home="${XDG_CONFIG_HOME:-${HOME}/.config}"
  local xdg_data_home="${XDG_DATA_HOME:-${HOME}/.local/share}"
  local _new_tmuxedo_plugins="${xdg_data_home}/tmuxedo/plugins"
  local _old_tmuxedo_plugins="${xdg_config_home}/tmux/plugins"
  local plugin_name="$1"

  if [ -d "$_new_tmuxedo_plugins/$plugin_name" ]; then
    echo "$_new_tmuxedo_plugins/$plugin_name"
  elif [ -d "$_old_tmuxedo_plugins/$plugin_name" ]; then
    echo "$_old_tmuxedo_plugins/$plugin_name"
  else
    echo ""
  fi
}

has_plugin() {
  local plugin_name="$1"
  if [ -d "$(get_dir_for_plugin "$plugin_name")" ]; then
    return 0
  else
    return 2
  fi
}

if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then
  has_plugin; exit $?
fi
