{{- if ne .chezmoi.os "darwin" }}
[".config/bash-it"]
  type = "archive"
  url = "https://github.com/Bash-it/bash-it/archive/refs/tags/v3.2.0.tar.gz"
  stripComponents = 1
  exclude = [
    "enabled/*",
    "custom/*",
    "profiles/*",
  ]
{{- end }}
